# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/alvapresbitero" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alva Presbitero
user_description: I am a senior data scientist and research specialist with a rich experience in solving various problems ranging from biological systems, political dynasties, and cities through data science and computational modeling. Currently, I am one of the lead scientists on a smart city project in the Philippines. I hold a double-degree PhD in Computational Science from the University of Amsterdam and ITMO University.
user_title: Scientist
email: lpresbitero@aim.edu
twitter_username: louella__alva
github_username:  avpresbitero
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "avpresbitero"

exclude: ['package.json', 'src' , 'node_modules']

domain: avpresbitero.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://avpresbitero.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /avpresbitero/      # place folder name if the site is served in a subfolder   